name: Lint & compile

on:
  push:
    paths: 
      - '**/*.tex'

env:
  BUNDLE: compiled

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: LaTeX linter (chktex)
        uses: j2kun/chktex-action@1.0.3
  compile:
    strategy:
      matrix:
        target-files: [test1.tex, test2.tex]
    runs-on: ubuntu-latest
    steps:
      # - name: Set up Git repository
      #   uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: ${{ matrix.target-files }}
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
  publish:
    runs-on: ubuntu-latest
    steps:
      # - name: Set up Git repository
      #   uses: actions/checkout@v1
      - name: Collect artifacts
        run: |
          rm -rf artifacts
          mkdir -p artifacts/$BUNDLE
          mv *.pdf artifacts/$BUNDLE
      - name: Save artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.BUNDLE }}
          path: artifacts
