name: Compile

on:
  push:
    tags:
      - "v*"

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Compile LaTeX document 1
        uses: dante-ev/latex-action@master
        with:
          root_file: test1.tex
          args: -interaction=nonstopmode -shell-escape
      - name: Compile LaTeX document 2
        uses: dante-ev/latex-action@master
        with:
          root_file: test2.tex
          args: -interaction=nonstopmode -shell-escape
      - name: Collect artifacts
        run: |
          rm -rf out
          mkdir -p out
          mv *.pdf out
      - name: Save artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: compiled files
          path: out/
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: out/*.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
